### ISSUE TITLE
`TryParseTokenUnsafe(out long value)` does not handle -9223372036854775808

### ISSUE THREAD

**Issue by summivox** [Microsoft/Microsoft.Shared.Dna.Json#1]
https://github.com/Microsoft/Microsoft.Shared.Dna.Json/blob/master/Microsoft.Shared.Dna.Json/JsonParser.cs#L1272

Because `accumulator` is positive, it cannot accept 9223372036854775808.

EDIT: stupid typo

EDIT: `accumulator = sign * accumulator` is missing `checked` for `OverflowException`

**Comment by rich-b-daniel** [comment]
Fix tested, reviewed, and integrated.
